### PR TITLE
Performance: Responsive Images is now fast!

### PR DESCRIPTION
**Pull request by onlymejosh**
Running gulp responsive-images now runs about 100x faster.

```
gulp responsive-images  108.11s user 3.93s system 166% cpu 1:07.48 total
```

Now:

```
gulp responsive-images  5.82s user 1.79s system 68% cpu 11.167 total
```

Much :heart: to @callumacrae :tada:  for figuring it out!!

The issue was ordering of the pipes. We need to make sure the files are renamed, then checked for change before handling resize or optimisation

:tada: :tada: :tada: :tada: :tada: :tada: :tada:

### CODE REVIEW

**Comment by urbanautomaton** [comment]
Nice one. :+1: 

Interestingly, the pipes were originally this way around, and got switched some time back in March: https://github.com/Lostmyname/lmn-gulp-tasks/commit/92bc8e2013542d3e42585d7eea7a71f893ab80e5

@callumacrae, I don't suppose you remember what was going wrong with the resizing that necessitated that change in the order?

**Comment by callumacrae** [comment]
Little issue (also mentioned on Slack): images generated from @2x images will be as twice as big as they need to be as the check for `@2x` in the filename will always fail. The way to fix that is to save the old file name before renaming it and calling gm directly, looking for the new property instead of `file.path`.

**Comment by callumacrae** [comment]
@urbanautomaton Basically exactly what I just said, I think. Didn't remember until now and thought checking for `-xlarge` would be okay, but it wouldn't be

**Comment by callumacrae** [comment]
If the test failure was the same as on master, rebasing onto master should fix it.

**Comment by callumacrae** [comment]
@onlymejosh Can you test this tomorrow? It's working for me locally (now tested on the actual website).

**Comment by callumacrae** [comment]
Rerunning the tests then merging and releasing :+1:

**Comment by onlymejosh** [comment]
Im just about to push this to staging to test :)

**Comment by callumacrae** [comment]
Cool, let me know when it's up

**Pull request merged**
